debug_plot: True
debug_data: True

year: 2015

input_path_data_nc: "/work/ab0995/a270088/sisters/runs/F12/ssh.fesom.2015.nc"
input_path_grid_nc: "/work/ab0995/a270088/meshes/FORCA12/fesom.mesh.diag.nc"

input_left: -70
input_right: 30
input_top: -20
input_bottom: -60

output_path_grid_subset: "/work/ab0995/b382485/eddy_data/mesh_subset.nc"
