input_subset_pre_processed: "/work/ab0995/b382485/eddy_data/subset_pre_proc"
input_subset_grid: "/work/ab0995/b382485/eddy_data/subset_pre_proc/subset_mesh.nc"

train_prop: 70
val_prop: 20
test_prop: 10

train_batch_size: 256
val_batch_size: 32
test_batch_size: 32

n_features: 1
hid_channels: 8
n_classes: 3

final_act: "softmax" # "sigmoid", "linear"
loss_op: "WCE" # "CE"
optimizer: "Adam"
learn_rate: 0.005

# Decides whether to show the graphical results or to same them in a folder
plot_show: False

plot_vertical: True

output_images_path: "/work/ab0995/b382485/eddy_data/subset_pre_proc/image_results"
