#input_subset_pre_processed: "/work/ab0995/b382485/eddy_data/reduced_roi/pre_proc_train"
#input_subset_grid: "/work/ab0995/b382485/eddy_data/reduced_roi/pre_proc_train/subset_mesh.nc"
#output_images_path: "/work/ab0995/b382485/eddy_data/reduced_roi/pre_proc_train/image_results"

input_subset_pre_processed: "/work/ab0995/b382485/eddy_data/original_roi/pre_proc_train"
input_subset_grid: "/work/ab0995/b382485/eddy_data/original_roi/pre_proc_train/subset_mesh.nc"
output_images_path: "/work/ab0995/b382485/eddy_data/original_roi/pre_proc_train/image_results"

dataset_size: 4017

train_prop: 80
val_prop: 10
test_prop: 10

train_batch_size: 16
val_batch_size: 16
test_batch_size: 16

n_features: 1
hid_channels: 16
n_classes: 3

final_act: "softmax" # "sigmoid" "linear"
loss_op: "Dice" #"WCE" # "CE"
loss_weight_1: 1
loss_weight_2: 9
loss_weight_3: 8

optimizer: "Adam"
learn_rate: 0.001

epochs: 20

# True: shows the graphical results. False: saves them in a folder
plot_show: True
plot_number: 7
