input_subset_pre_processed: "/work/ab0995/b382485/eddy_data/subset_pre_proc"
input_subset_grid: "/work/ab0995/b382485/eddy_data/subset_pre_proc/subset_mesh.nc"

train_prop: 70
val_prop: 20
test_prop: 10

train_batch_size: 32
val_batch_size: 32
test_batch_size: 32

n_features: 1
hid_channels: 32
n_classes: 3

final_act: "sigmoid" # "linear"
loss_op: "CE"
optimizer: "Adam"
learn_rate: 0.005

plot_show: True
plot_vertical: True

output_images_path: "/work/ab0995/b382485/eddy_data/subset_pre_proc/image_results"
