year: 2015

input_path_ssh_seg_masks: "/work/ab0995/b382485/eddy_data/reduced_roi/segmentation_masks"
input_grid_nc: "/work/ab0995/a270088/meshes/FORCA12/fesom.mesh.diag.nc"

input_left: -70
input_right: -20
#30
input_top: -40
#-20
input_bottom: -60

output_mesh: "subset_mesh.nc"
output_subset_pre_proc: "/work/ab0995/b382485/eddy_data/reduced_roi/pre_proc_train/"
output_subset_pre_proc_raw: "/work/ab0995/b382485/eddy_data/reduced_roi/pre_proc_train/raw"
