input_subset_pre_processed: "/work/ab0995/b382485/eddy_data/subset_pre_proc"
input_subset_grid: "/work/ab0995/b382485/eddy_data/subset_pre_proc/mesh_subset.nc"

input_left: -70
input_right: 30
input_top: -20
input_bottom: -60

hid_channels: 32
n_classes: 1
train_batch_size: 512
test_batch_size: 512
valid_batch_size: 512
final_act: "sigmoid" # "linear"
