debug_plot: False
debug_data: False

year: 2015

input_path_data_filtered: "/work/ab0995/b382485/eddy_data/output_path/months"
input_path_data_seg_masks: "/work/ab0995/b382485/eddy_data/segmentation_masks"
input_grid_nc: "/work/ab0995/a270088/meshes/FORCA12/fesom.mesh.diag.nc"

input_left: -70
input_right: 30
input_top: -20
input_bottom: -60

output_subset_pre_processed: "/work/ab0995/b382485/eddy_data/subset_pre_processed"
